// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rate-limiter.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Ratelimiter {
  public static partial class RateLimiter
  {
    static readonly string __ServiceName = "ratelimiter.RateLimiter";

    static readonly grpc::Marshaller<global::Ratelimiter.Request> __Marshaller_Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ratelimiter.Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Ratelimiter.State> __Marshaller_State = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ratelimiter.State.Parser.ParseFrom);

    static readonly grpc::Method<global::Ratelimiter.Request, global::Ratelimiter.State> __Method_checkRequest = new grpc::Method<global::Ratelimiter.Request, global::Ratelimiter.State>(
        grpc::MethodType.Unary,
        __ServiceName,
        "checkRequest",
        __Marshaller_Request,
        __Marshaller_State);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ratelimiter.RateLimiterReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RateLimiter</summary>
    public abstract partial class RateLimiterBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Ratelimiter.State> checkRequest(global::Ratelimiter.Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RateLimiter</summary>
    public partial class RateLimiterClient : grpc::ClientBase<RateLimiterClient>
    {
      /// <summary>Creates a new client for RateLimiter</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public RateLimiterClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RateLimiter that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public RateLimiterClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected RateLimiterClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected RateLimiterClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Ratelimiter.State checkRequest(global::Ratelimiter.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return checkRequest(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Ratelimiter.State checkRequest(global::Ratelimiter.Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_checkRequest, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Ratelimiter.State> checkRequestAsync(global::Ratelimiter.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return checkRequestAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Ratelimiter.State> checkRequestAsync(global::Ratelimiter.Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_checkRequest, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override RateLimiterClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RateLimiterClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(RateLimiterBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_checkRequest, serviceImpl.checkRequest).Build();
    }

  }
}
#endregion
